import { Announcement, Rifugio } from './types';

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    type: 'offro',
    status: 'pubblicato',
    title: 'Cercasi cuoco/a per stagione estiva',
    description: 'Il Rifugio Stella Alpina cerca un cuoco/a con esperienza in cucina di montagna per la stagione estiva 2025. Si richiede capacità di gestione autonoma della cucina per 40 coperti. Vitto e alloggio inclusi.',
    contactName: 'Marco Bernardi',
    email: 'info@rifugiostellaalpina.it',
    phone: '333 1234567',
    region: 'Trentino-Alto Adige',
    season: 'Estate 2025',
    rifugioName: 'Rifugio Stella Alpina',
    roleSought: 'Cuoco/a',
    website: 'www.rifugiostellaalpina.it',
    createdAt: '2025-03-15',
  },
  {
    id: '2',
    type: 'offro',
    status: 'pubblicato',
    title: 'Aiuto rifugista per Rifugio Monte Chiaro',
    description: 'Cerchiamo una persona motivata come aiuto rifugista per la stagione estiva. Mansioni: accoglienza ospiti, servizio ai tavoli, pulizia locali. Esperienza precedente apprezzata ma non indispensabile. Ambiente familiare.',
    contactName: 'Elena Rossi',
    email: 'elena@rifugiomonte chiaro.it',
    phone: '345 9876543',
    region: 'Lombardia',
    season: 'Estate 2025',
    rifugioName: 'Rifugio Monte Chiaro',
    roleSought: 'Aiuto rifugista',
    createdAt: '2025-03-20',
  },
  {
    id: '3',
    type: 'offro',
    status: 'pubblicato',
    title: 'Cameriere/a al Rifugio Aquila Reale',
    description: 'Il Rifugio Aquila Reale cerca cameriere/a per il servizio ristorante e bar. Periodo da metà giugno a fine settembre. Richiesta buona conoscenza del tedesco. Contratto regolare, vitto e alloggio.',
    contactName: 'Thomas Hofer',
    email: 'info@aquilareale.com',
    phone: '347 5551234',
    region: 'Trentino-Alto Adige',
    season: 'Estate 2025',
    rifugioName: 'Rifugio Aquila Reale',
    roleSought: 'Cameriere/a',
    website: 'www.aquilareale.com',
    createdAt: '2025-03-22',
  },
  {
    id: '4',
    type: 'cerco',
    status: 'pubblicato',
    title: 'Cuoco con esperienza cerca stagione estiva',
    description: 'Cuoco con 5 anni di esperienza in rifugi alpini, specializzato in cucina tradizionale di montagna e gestione autonoma della cucina. Disponibile da giugno a settembre. Referenze disponibili.',
    contactName: 'Giovanni M.',
    email: 'giovanni.m@email.it',
    phone: '339 8765432',
    region: 'Piemonte',
    season: 'Estate 2025',
    desiredRole: 'Cuoco/a',
    experience: '5 anni in rifugi alpini',
    preferredArea: 'Alpi Occidentali',
    availability: 'Giugno - Settembre 2025',
    createdAt: '2025-03-18',
  },
  {
    id: '5',
    type: 'cerco',
    status: 'pubblicato',
    title: 'Ragazza cerca prima esperienza in rifugio',
    description: 'Studentessa universitaria, 23 anni, appassionata di montagna. Cerco prima esperienza come aiuto rifugista o cameriera. Sono disponibile, motivata e abituata alla vita in quota. Disponibile per tutta l\'estate.',
    contactName: 'Sara L.',
    email: 'sara.l@email.it',
    phone: '340 1122334',
    region: 'Veneto',
    season: 'Estate 2025',
    desiredRole: 'Aiuto rifugista',
    experience: 'Prima esperienza',
    preferredArea: 'Dolomiti',
    availability: 'Giugno - Settembre 2025',
    createdAt: '2025-03-25',
  },
  {
    id: '6',
    type: 'cerco',
    status: 'pubblicato',
    title: 'Tuttofare esperto cerca lavoro stagionale',
    description: 'Uomo di 35 anni con esperienza pluriennale in manutenzione, piccole riparazioni, gestione magazzino e logistica in ambiente montano. Patente B, automunito. Disponibile anche per stagioni invernali.',
    contactName: 'Paolo R.',
    email: 'paolo.r@email.it',
    phone: '328 9988776',
    region: 'Valle d\'Aosta',
    season: 'Estate 2025',
    desiredRole: 'Tuttofare',
    experience: '8 anni in strutture montane',
    preferredArea: 'Gran Paradiso / Monte Bianco',
    availability: 'Maggio - Ottobre 2025',
    createdAt: '2025-03-28',
  },
  {
    id: '7',
    type: 'offro',
    status: 'in_attesa',
    title: 'Barista per rifugio in Dolomiti',
    description: 'Cercasi barista per servizio bar e piccola cucina. Rifugio a 2200m, raggiungibile solo a piedi.',
    contactName: 'Anna Bianchi',
    email: 'anna@rifugiodolomiti.it',
    phone: '333 4445556',
    region: 'Veneto',
    season: 'Estate 2025',
    rifugioName: 'Rifugio Val di Sole',
    roleSought: 'Barista',
    createdAt: '2025-04-01',
  },
];

export const mockRifugi: Rifugio[] = [
  {
    id: '1',
    name: 'Rifugio Stella Alpina',
    region: 'Trentino-Alto Adige',
    province: 'Trento',
    mountainRange: 'Dolomiti',
    altitude: 2165,
    description: 'Storico rifugio situato nel cuore delle Dolomiti di Brenta, punto di partenza ideale per escursioni e vie ferrate. La cucina propone piatti tipici trentini preparati con ingredienti locali. Atmosfera familiare e accogliente.',
    services: ['Pernottamento', 'Ristorante', 'Bar', 'Docce calde', 'Punto ricarica'],
    access: 'Raggiungibile a piedi dal parcheggio di Vallesinella in circa 2 ore di cammino.',
    contacts: 'Tel: 0465 441234 - Email: info@rifugiostellaalpina.it',
    website: 'www.rifugiostellaalpina.it',
    images: [],
  },
  {
    id: '2',
    name: 'Rifugio Monte Chiaro',
    region: 'Lombardia',
    province: 'Brescia',
    mountainRange: 'Adamello-Presanella',
    altitude: 1890,
    description: 'Accogliente rifugio ai piedi del ghiacciaio dell\'Adamello. Base perfetta per escursioni estive e scialpinismo invernale. Gestione familiare da tre generazioni, cucina casalinga genuina.',
    services: ['Pernottamento', 'Ristorante', 'Bar', 'Locale invernale'],
    access: 'Da Ponte di Legno, sentiero CAI 1 in circa 1h30.',
    contacts: 'Tel: 0364 991234 - Email: info@rifugiomontechiaro.it',
    website: 'www.rifugiomontechiaro.it',
    images: [],
  },
  {
    id: '3',
    name: 'Rifugio Aquila Reale',
    region: 'Trentino-Alto Adige',
    province: 'Bolzano',
    mountainRange: 'Dolomiti',
    altitude: 2450,
    description: 'Rifugio panoramico con vista mozzafiato sulle Tre Cime. Punto strategico per l\'Alta Via n.1 delle Dolomiti. Cucina altoatesina con specialità come canederli e strudel. Wi-Fi disponibile.',
    services: ['Pernottamento', 'Ristorante', 'Bar', 'Docce calde', 'Wi-Fi', 'Punto ricarica'],
    access: 'Raggiungibile dal Rifugio Auronzo in circa 1h15 di sentiero ben segnalato.',
    contacts: 'Tel: 0474 661234 - Email: info@aquilareale.com',
    website: 'www.aquilareale.com',
    images: [],
  },
  {
    id: '4',
    name: 'Rifugio Gran Paradiso',
    region: 'Valle d\'Aosta',
    province: 'Aosta',
    mountainRange: 'Gran Paradiso',
    altitude: 2732,
    description: 'Rifugio storico sulla via normale al Gran Paradiso, il 4000 più accessibile delle Alpi. Punto di appoggio fondamentale per alpinisti. Ambiente spartano ma accogliente, cucina energetica per gli scalatori.',
    services: ['Pernottamento', 'Ristorante', 'Locale invernale', 'Eliporto'],
    access: 'Da Pont, sentiero in circa 3h30. Ultimo tratto su morena.',
    contacts: 'Tel: 0165 741234 - Email: info@rifugiogranparadiso.it',
    website: 'www.rifugiogranparadiso.it',
    images: [],
  },
  {
    id: '5',
    name: 'Rifugio Bosco Verde',
    region: 'Piemonte',
    province: 'Cuneo',
    mountainRange: 'Alpi Occidentali',
    altitude: 1650,
    description: 'Rifugio immerso nei boschi di larici della Val Maira. Ideale per famiglie e amanti della natura. Cucina occitana con prodotti a km zero. Punto di partenza per il Sentiero dei Ciclamini.',
    services: ['Pernottamento', 'Ristorante', 'Bar', 'Posto tenda', 'Docce calde'],
    access: 'Raggiungibile in auto fino al parcheggio, poi 20 minuti a piedi.',
    contacts: 'Tel: 0171 881234 - Email: info@rifugioboscoverde.it',
    website: 'www.rifugioboscoverde.it',
    images: [],
  },
  {
    id: '6',
    name: 'Bivacco Cima Rossa',
    region: 'Lombardia',
    province: 'Sondrio',
    mountainRange: 'Alpi Centrali',
    altitude: 3100,
    description: 'Bivacco metallico incustodito a quota 3100m. Capienza 9 posti letto. Struttura essenziale ma in buone condizioni. Panorama straordinario sulla catena del Bernina. Solo per escursionisti esperti.',
    services: ['Locale invernale'],
    access: 'Da Chiareggio, sentiero alpinistico in circa 5 ore. Necessaria esperienza.',
    contacts: 'CAI Sondrio - Tel: 0342 221234',
    website: '',
    images: [],
  },
];
